### ISSUE TITLE
Reduce the number and size of dependencies

### ISSUE THREAD

**Issue by vicapow** [MyPureCloud/genesys-cloud-webrtc-sdk#26]
Adding this to a recent project and noticed the dependencies increased dramatically. One way to help mitigate this would be to better greenkeep the dependencies.

**Comment by vicapow** [comment]
As a quick example, it looks like `stupid-server` should be a dev dep

**Comment by xdumaine** [comment]
Echoing my comment on the other issue - we're in the process of migrating to typescript and upgrading all dependencies as well. stanza-io moving to 11 (and being renamed to stanza) Is a bigger change because it has to be factored into various build systems.

**Comment by xdumaine** [comment]
I'll definitely move stupid-server in the short term, that's an easy fix.

**Comment by xdumaine** [comment]
One thing to note is that this SDK is prioritizing features over size at the moment, and is actually planned to grow in the future. For a more lighter weight option, you could use the `streaming-client` directly, and implement the webrtc features on top of that. That is up for feedback however.

**Comment by djhouseknecht** [comment]
@vicapow v4.0.1 was released this morning. v3 would bundle all the sdk's dependencies into the built file. In v4 the dependencies are only bundled for the cdn version which should allow for consuming applications using a build tool to bundle the deps for the sdk. 

I know this doesn't necessarily reduce the number of dependencies, but it will reduce the number of duplicated dependencies. Also, the code can be transpiled to the needs of the consuming app.

If you have any issues or questions, let us know. Thanks!
