### ISSUE TITLE
two conversations mail instead of one

### ISSUE THREAD

**Issue by CharlotteH59** [MyPureCloud/genesys-cloud-webrtc-sdk#520]
Hello

We use your Pure Cloud solution to discuss with customers.
But I noticed something strange :

- we send an email to the customer's mail Mail@test.com
- the customer answers but with the mail mail@test.com

It makes 2 different conversations instead of one (with 2 participants).
It gives 2 lines in the view "interactions" instead of one.

If the customer answers with the mail Mail@test.com, it seems to have only 1 conversation.
But an email adress is always insensitive of the case... Can you be insensitive to the case too ?

Thank you for your answer.

**Comment by jensengar** [comment]
@CharlotteH59 this library is strictly for webrtc interactions, does your issue relate to that in some way?

**Comment by CharlotteH59** [comment]
sorry, in fact it doesn't relate about webRTC
