### ISSUE TITLE
pendingSession not firing with version 6.1.0

### ISSUE THREAD

**Issue by bdbvb** [MyPureCloud/genesys-cloud-webrtc-sdk#620]
I've got the webrtc sdk working with version 6.0.1, but when I update to version 6.1.0, the "pendingSession" event no longer fires when an incoming call is offered, so I can't pick up the call. Reverting back to 6.0.1, it works again.

Are there any code changes I need to make with 6.1.0 to get that to work, or is it a regression?

Thanks!

```
const client = new GenesysCloudWebrtcSdk({
    accessToken: accessToken,
    environment: localState.config.regionHost,
    allowedSessionTypes: [SessionTypes.softphone]
});
...
client.on("pendingSession", pendingSession => {
     /*this callback not getting fired/*
     myClient.acceptPendingSession(pendingSession.id); // promise
});
...
await client.initialize();
...
```

**Comment by jensengar** [comment]
I will look at this today.

**Comment by jensengar** [comment]
I didn't get around to checking 6.1.0, bug 6.1.1 is definitely firing the `pendingSession` events.
