### ISSUE TITLE
IPendingSession.address is the address of the person receiving an incoming call

### ISSUE THREAD

**Issue by PRevakgreenWGU** [MyPureCloud/genesys-cloud-webrtc-sdk#626]
Description in documentation for IPendingSession.address is "address: string – the address of the caller"

However, console.log-ing the session.address just outputs the address of the person receiving the call.

**Comment by jensengar** [comment]
You're right. Let me see what we can do about this. Upon looking at this, I'm not sure we actually have the caller/callee information.

**Comment by jensengar** [comment]
@PRevakgreenWGU after some investigation I've determined this is actually an internal property that doesn't really mean anything useful for the SDK. I apologize for the confusion. We are going to remove this property and fix the doc in v7.

**Comment by djhouseknecht** [comment]
We released v7.0.0 which renames `pendingSession.address` back to what is actually sent to us from the server which is `pendingSession.fromJid`. Documentation should be updated to show this change. Closing this issue out.
