### ISSUE TITLE
Dependency "Stanza" References Node 14 (--> TS compilation conflict if using 16)

### ISSUE THREAD

**Issue by bdbvb** [MyPureCloud/genesys-cloud-webrtc-sdk#644]
genesys-cloud-streaming-client (6.1.6) takes a dependency on genesys-cloud-streaming-client (^13.3.7, currently 13.4.0), which takes a dependency on stanza (^12.17.2).

stanza depends on @types/node: ^14.14.36

That seems to be a problem when my client software takes a dependency on a different version of @types/node (typescript compilation complains about conflicting definitions). I'm using node 16, which is the current stable version.

A workaround for now is for me to explicitly take a dependency on @types/node: ^14.14.36 (actually ^14.17.34), instead of a 16 version, and it seems to work ok, but isn't ideal obviously since it doesn't match the actual environment (16). Another workaround (even less desirable) is setting "skipLibCheck": false in tsconfig.json.

In my package-lock.json file, all of the other third-party libraries that depend on @types/node specify "*" for the version... except for stanza.

I don't see that many people using stanza, so maybe there's a substitute for that that plays more nicely? Their github page doesn't seem to accept issues either. 

The above workaround is OK for now, but it's not ideal.

Thanks!

**Comment by djhouseknecht** [comment]
Thanks for the report @bdbvb. I wasn't able to reproduce this error. I tried creating a new typescript project with dependencies on `genesys-cloud-webrtc-sdk` and `@types/node ^16` but it was able to compile. 

Could you throw together a reproduction repo? I am guessing I am probably missing some kind of tsconfig option that is triggering this error.

**Comment by bdbvb** [comment]
Thanks @djhouseknecht. I uploaded a private github repo and added you as a collaborator. Let me know if that helps you to reproduce the issue. Note that I'm using Node 17.3.1.

**Comment by bdbvb** [comment]
It seems that merely running npm update resolves the issue. Not sure which updated dependency makes it work, but I seem to be past that error now.

**Comment by djhouseknecht** [comment]
That is good news, @bdbvb. I wouldn't be surprised if if it was a minor version of TS that fixed it. They are notorious for releasing a lot of breaking changes since they don't follow the standard semver pattern. I am going to leave this open because we still have some node version issues to solve in the sdk with some other things. I want to make sure that this doesn't pop back up.
