### ISSUE TITLE
Initialization: Logging Errors and partner key info message

### ISSUE THREAD

**Issue by bdbvb** [MyPureCloud/genesys-cloud-webrtc-sdk#693]
I had this library working a few months ago but have been off the GC platform for a while and am now coming back to it, using the latest version. 

I'm able to get connected, but I'm seeing some console logging on initialization that I didn't see before.

The code would be:

        const client = new GenesysCloudWebrtcSdk({
                    accessToken: accessToken,
                    environment: localState.config.regionHost,
                    allowedSessionTypes: [SessionTypes.softphone]
                });
        ... (some other setup)
        await client.initialize();

And the console logging in question:

        No partner key provided.
        
        Add keys to the config object on initialization.
        E.g. await init({
          partnerKey: 'my-partner-key-from-developer-zone',
          appId: 'my-self-chosen-app-id',
          appName: 'My App Name'
        });

        Please obtain a valid partner key from https://developer.jabra.com.
        The key will ensure interoperability with other Jabra apps and services, and mitigate
        some co-existence issues with other softphone applications.

        The package will continue to work without the keys, but we do not recommend production release
        without it. Read more on the Developer Zone.

and errors like the following:

        react_devtools_backend.js:3973 [streaming-client] Error sending logs to server Error: {"message":"App not authorized to use scope [diagnostic]","code":"app.not.authorized.for.scope","status":403,"contextId":"7133609b-4a63-40c7-8daf-2ceee6b9f07d","details":[],"errors":[]}
            at Request.<anonymous> (client.js:467:1)
            at Request.Emitter.emit (index.js:145:1)
            at Object.xhr.onreadystatechange (client.js:801:1)
            at Object.t.<computed> [as dispatchEvent] (inject.js:1:4952)
            at r (inject.js:1:7395)
            at n (inject.js:1:7699)
            at n (inject.js:1:7659)
            at m (inject.js:1:7705)
            at XMLHttpRequest._.onreadystatechange (inject.js:1:7834)

For the former, I'm not using a headset, so I'm not sure why it's telling me this.

For the latter (the error), it seems like maybe the app needs another OAuth scope called "diagnostic" but I don't see such a scope in the Genesys Cloud OAuth admin area. Anything I need to do to have the telemetry work? Where does that telemetry show up anyway?

Thanks!

**Comment by djhouseknecht** [comment]
@bdbvb thanks for the report. 

For the 1st report (`No partner key provided.`), that was introduced when we added support for headset functionality. It is a little annoying to have that show up every time, though. We will create a ticket and tune down that logging. 

For the 2nd, I'm not 100% sure how to go about getting the `diagnostic` scope applied. I could ask our auth team if you would like. But to get around it, just instantiate the sdk with `optOutOfTelemetry: true` like: 
``` ts
const client = new GenesysCloudWebrtcSdk({
    accessToken: accessToken,
    environment: localState.config.regionHost,
    allowedSessionTypes: [SessionTypes.softphone],
    optOutOfTelemetry: true // <- add this
});
```
That will keep the sdk from trying to send it's logs to the server.
